dist: xenial
language: python
cache: pip

matrix:
  include:
    - env:
        - TOXENV=py35
      python: "3.5"
    - env:
        - TOXENV=py36
      python: "3.6"
    - env:
        - TOXENV=py37
      python: "3.7"
    - env:
        - TOXENV=py38
      python: "3.8"
    - env:
        - TOXENV=py38-dev
      python: "3.8-dev"
    - env:
        - TOXENV=py35
      python: "3.5"
    - env:
        - TOXENV=py36
      python: "3.6"
    - env:
        - TOXENV=py37
      python: "3.7"
    - env:
        - TOXENV=py38
      python: "3.8"
    - env:
        - TOXENV=py38-dev
      python: "3.8-dev"
    - env:
        - TOXENV=py35
      python: "3.5"
    - env:
        - TOXENV=py36
      python: "3.6"
    - env:
        - TOXENV=py37
      python: "3.7"
    - env:
        - TOXENV=py38
      python: "3.8"
    - env:
        - TOXENV=py38-dev
      python: "3.8-dev"
    - env:
        - TOXENV=py35
      python: "3.5"
    - env:
        - TOXENV=py36
      python: "3.6"
    - env:
        - TOXENV=py37
      python: "3.7"
    - env:
        - TOXENV=py38
      python: "3.8"
    - env:
        - TOXENV=py38-dev
      python: "3.8-dev"

install:
  - pip install -U codecov
  - pip install -U tox-travis
  - pip install -e .

before_script:
  - python -VV

script:
  - tox

env:
  - CODECOV_TOKEN="9d4d4fe4-5c54-4e22-a5e4-cdf6d6442b79"

after_success:
  - codecov