"""Module version and author info."""
__title__ = "termania"
__description__ = "A Python interface for the Termania.net dictionary API"
__url__ = "https://github.com/techouse/termania-api"
__version__ = "1.0.2"
__author__ = "Klemen Tusar"
__author_email__ = "techouse@gmail.com"
__license__ = "MIT"
